#!inc geocall/base.properties
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPPRODUTTORE {VARCHAR 30}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPPRODUTTORE1 {VARCHAR 20}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLPAC {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLMCL {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPCALIBRE {VARCHAR 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPMETERDESCRIPTION {VARCHAR 30}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLCSP {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPLDN {VARCHAR 20}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPYCOORD {NUMBER 11 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPXCOORD {NUMBER 11 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPDRPRE609 {VARCHAR 50}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPTELCOVERAGE {VARCHAR 10}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLFCL {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPVALVESTATUS {VARCHAR 10}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPNUMERATORGROUP {VARCHAR 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPNUMDECPLACES {NUMBER 2 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLDFE {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPINITIALPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPSUPPLYPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPTECHNICALPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPPOWERBLOCKARREARS {CHAR 1}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPVALVEKEY {CHAR 1}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPBUILDINGKEYS {CHAR 1}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPSHELF {CHAR 1}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLSAR {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPPRECONFIGUREDFLAG {CHAR 1}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPPERFORMANCEPRESSURE {VARCHAR 10}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLCTE {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPID_XHWFLPTY {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPFIRSTREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPFIRSTREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPSECONDREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPSECONDREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPTHIRDREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPTHIRDREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPRF {VARCHAR 10}}
/
{ALTER_ADD_COLUMN AIMPIANTI XHWFAIMPRX {VARCHAR 10}}
/
