#!inc geocall/base.properties
{ALTER_ADD_COLUMN ERSGG XHWFAIMPPRODUTTORE {VARCHAR 30}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPPRODUTTORE1 {VARCHAR 20}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLPAC {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLMCL {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPCALIBRE {VARCHAR 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPMETERDESCRIPTION {VARCHAR 30}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLCSP {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPLDN {VARCHAR 20}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPYCOORD {NUMBER 11 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPXCOORD {NUMBER 11 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPDRPRE609 {VARCHAR 50}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPTELCOVERAGE {VARCHAR 10}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLFCL {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPVALVESTATUS {VARCHAR 10}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPNUMERATORGROUP {VARCHAR 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPNUMDECPLACES {NUMBER 2 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLDFE {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPINITIALPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPSUPPLYPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPTECHNICALPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPPOWERBLOCKARREARS {CHAR 1}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPVALVEKEY {CHAR 1}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPBUILDINGKEYS {CHAR 1}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPSHELF {CHAR 1}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLSAR {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPPRECONFIGUREDFLAG {CHAR 1}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPPERFORMANCEPRESSURE {VARCHAR 10}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLCTE {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPID_XHWFLPTY {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPFIRSTREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPFIRSTREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPSECONDREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPSECONDREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPTHIRDREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPTHIRDREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPRF {VARCHAR 10}}
/
{ALTER_ADD_COLUMN ERSGG XHWFAIMPRX {VARCHAR 10}}
/
