#!inc geocall/base.properties
{ALTER_ADD_COLUMN TEST XHWFAIMPPRODUTTORE {VARCHAR 30}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPPRODUTTORE1 {VARCHAR 20}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLPAC {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLMCL {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPCALIBRE {VARCHAR 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPMETERDESCRIPTION {VARCHAR 30}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLCSP {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPLDN {VARCHAR 20}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPYCOORD {NUMBER 11 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPXCOORD {NUMBER 11 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPDRPRE609 {VARCHAR 50}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPTELCOVERAGE {VARCHAR 10}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLFCL {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPVALVESTATUS {VARCHAR 10}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPNUMERATORGROUP {VARCHAR 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPNUMDECPLACES {NUMBER 2 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLDFE {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPINITIALPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPSUPPLYPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPTECHNICALPOWER {NUMBER 8 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPPOWERBLOCKARREARS {CHAR 1}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPVALVEKEY {CHAR 1}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPBUILDINGKEYS {CHAR 1}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPSHELF {CHAR 1}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLSAR {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPPRECONFIGUREDFLAG {CHAR 1}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPPERFORMANCEPRESSURE {VARCHAR 10}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLCTE {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPID_XHWFLPTY {NUMBER 10 0}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPFIRSTREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPFIRSTREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPSECONDREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPSECONDREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPTHIRDREADING {TIMESTAMP}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPTHIRDREADVALIDATION {NUMBER 9 8}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPRF {VARCHAR 10}}
/
{ALTER_ADD_COLUMN TEST XHWFAIMPRX {VARCHAR 10}}
/
